- index.js
**Changes:**
1. Adds a response when the user tries to access the route route of a running ProcessEngine instance.
The answer returns some properties from the `package.json` such as: 
* The application name
* The current running version
* The license
* The contriburots
**Issues:**
Closes #201 
PR: #211
Start the application and access `localhost:8000`.
You should no longer receive `Cannot GET /`, but a formatted JSON that contains the properties listed above.
> ✨ Add a Response when the User accesses the Root Route

- bpmn/process_model_name_mismatch.bpmn
- bpmn/process_model_too_many_processes.bpmn
- package-lock.json
- package.json
- test/2_management_api/process_models/update_process_definitions_by_name.js
- test/4_deployment_api/import_from_file.js
- test/4_deployment_api/import_from_xml_local.js
- test/4_deployment_api/import_from_xml_remotely.js
**Requires:**
https://github.com/process-engine/process_engine_core/pull/234
**Changes:**
1. Add more validations for ProcessModel deployment
- ProcessDefinitions must only contain one ProcessModel (Multiple ProcessModels are not supported right now)
- A ProcessModels ID must match the provided name under which the definition is to be stored (See linked issue).
2. Add some error logging to the `ProcessModelService`
3. Refactor the Integrationtests for the Deployment API to accommodate these new restrictions 
**Issues:**
Closes #219 
PR: #220
Try deploying a ProcessDefinition that breaks one of these new restrictions mentioned above. It should not be possible any longer.
> ✨ Add validations for ProcessModel persistence

- Jenkinsfile
- package.json
- src/main.ts
**Changes:**
1. use `__dirname` as the base path for the default config, to make it usable with the globally installed runtime
2. Add missing `env.` prefix to environment variable reference in Jenkinsfile
PR: #234
The configuration should now be loaded correctly with globally installed Runtimes.
> 🐛 Use __dirname as default config path

- package-lock.json
- package.json
**Changes:**
CallActivities are no longer run through the ConsumerAPI, but directly through the ExecuteProcessService.
**Issues:**
Closes #277
PR: #278
This is an internal refactoring, so everything should run as before.
Maybe a little faster, now that we don't have to run all the way through the Consumer API to run CallActivities.
> ♻️ Use ExecuteProcessService to run CallActivities

- scripts/post-migrations/7.1.1-fix_sqlite_database_contents.js
**Changes:**
Escape all special characters during the Post-migration script for Hotfix Version 7.1.1.
When dealing with ProcessModels that had `'` characters in them (like, say, when you have script task that performs something like `console.log('Hello');`, the SQLite query that moved the xml would fail with a parsing error.
This is because of the quotes contained in the `console.log` statement.
Escaping these characters fixes this issue.
PR: #299
Run the post-migration script on a a couple of databases that this script is supposed to fix.
> 🐛Escape special characters in xml during post migration

- Jenkinsfile
- package.json
1. 👷 Fix Wrong Usage of Credential Store
2. ⏪ Revert "🔥 👷 Disable building of windows installer"
3. ✨ Add Script For Only Building the Source 
Closes 5minds/process_engine_infrastructure#33
PR: #333
See https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fprocess_engine_runtime/detail/feature%2Ffix_builds/6/pipeline/287
> :construction_worker: Fix Builds 2

- package-lock.json
- package.json
1. Metrics for an ExternalTask will now get the task's actual payload, instead of the configured token expression.
2. The `on Suspend` token for each ExternalTask will also get the actual payload instead of the configured expression.
Closes #352
PR: #356
- Run a ProcessModel that uses ExternalTasks
- After the ExternalTask was run, examine the generated metrics for the ProcessModel
- See that ExternalTask's actual payload is put with the metrics, instead of the configured token expression
> ♻️ Store each ExternalTask's actual payload instead of the token expression

- config/mysql/iam/iam_service.json
- config/postgres/iam/iam_service.json
- config/sqlite/iam/iam_service.json
- config/test-mysql/iam/iam_service.json
- config/test-postgres/iam/iam_service.json
- config/test-sqlite/iam/iam_service.json
- package-lock.json
- package.json
1. Implement claim check caching into iam package
- Full Changelog `@process-engine/iam`: https://github.com/process-engine/iam/pull/11
2. Add production- and test- configs for claim check caching
- The default settings for the cache give a 5 minute lifetime for each cache entry and will tell the cache to clean itself up every 5 seconds
- **NOTE:** Since the tests use a mocked IAM service, the configs are never actually used. They were only added so that they mirror the production configs
Closes #358
PR: #361
The tests should all work as before.
For use in a productive environment, this is best tested with a setup that uses large amounts of BPMNs and/or BPMNs with multiple lanes.
You should notice a considerable increase in performance, when pulling these BPMNs frequently.
> ⚡️Add claim check caching

- Jenkinsfile
Move versioning to `find_available_version_for_publish`. 
This function will keep trying `npm version`, until a version is found that is available on npm. 
Note that this is only done on `develop` and `feature` branches. The master is not affected.
PR: #372
Kinda hard to test, as this error only happened sporadically. 
We'll just have to see how this will perform in the long run.
> 👷 Fix "you cannot publish over existing version" issue 

- bpmn/cyclic_timers_test_no_enabled_property.bpmn
- package-lock.json
- package.json
- test/1_process_engine/start_event_cyclic_timers_tests.js
Fix an issue that prevented TimerDefinitions from being parsed, if the corresponding XML is missing an `enabled` CamundaProperty.
PR: #375
- Upload a ProcessModel with any kind of TimerEvent that is missing a CamundaProperty `enabled`
- Make a `Get ProcessModels` call
- See that you'll get a list of your ProcessModels
> 🐛 Fix timer event parsing

- package-lock.json
- package.json
1. Decouple the ManagementApiCore from the ConsumerApi
2. Add customized implementations for all services that previously used the Consumer API
- These services are implemented in the same way their counterparts from the ConsumerAPI are
PR #385
The end user shouldn't notice any differences.
> 🔥Disconnect ManagementApi from ConsumerApi

- Jenkinsfile
- test/1_process_engine/parallel_gateway_test.js
- test/5_metrics_api/metrics_api_test.js
1. Use default SQLite storage path during CI builds.
2. Remove Management API references from ParallelGateway tests
3. Add buffer to MetricsAPI tests to avoid sync errors
4. Cleanup after the `Build Windows Installer` and `SQLite Test` steps
PR: #402
Watch some CI builds.
https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fprocess_engine_runtime/detail/feature%2Fuse_default_storage_path_for_sqlite_databases/1/pipeline/72
> 👷 Use default SQLite storage path

- config/mysql/iam/iam_service.json
- config/postgres/iam/iam_service.json
- config/sqlite/iam/iam_service.json
- config/test-mysql/iam/iam_service.json
- config/test-postgres/iam/iam_service.json
- config/test-sqlite/iam/iam_service.json
- package-lock.json
- package.json
1. Adds the `allowGodToken` config option to the IamService's config, which can be used to allow or disallow the use of the "dummy token".
2. Allow dummy token per default for all test environments
3. Disallow dummy token per default for all production environments, except SQLite
-  We can't do that yet, because this is the default Config for the BPMN Studio, which does not yet have a mechanism for updating its config at startup
- This will be changed as soon as the Studio is able to make adjustments to the runtime's config
Closes #414
PR: #416
- Make requests with the dummy token against the runtime, while using an environment that has `allowGodToken` set to false.
- This shouldn't work anymore.
> 🔧 Add "allowGodToken" config for iam service

- Jenkinsfile
- package-lock.json
- package.json
1. Reduce log spamming, when using test environments
2. Store claim check results by a users token, instead of a userId
Part of https://github.com/process-engine/process_engine_runtime/issues/419
PR: #420
- Make claim check requests for the same user, using different tokens with varying permissions
- See that the results are all correct
> 🐛 Betafix: Cache by token instead of UserId

- package-lock.json
- src/main.ts
Bootstrapper errors will now cause the runtime to exit with an error.
Closes #423
PR: #424
- Delete some of your configs or register something invalid at the ioc container
- Start up the runtime
- See that the bootstrapper throws an error and the process exits with error code 1
> 🐛 Terminate runtime when the bootstrapper fails to start

- .npmignore
- Jenkinsfile
- installer/README.md
- package-lock.json
- package.json
- scripts/pack_sources/exec_async.js
- scripts/pack_sources/pack_to_tarball.js
- scripts/pack_sources/pack_to_zip.js
1. `Prepare Version` now only prepares the version for the package.json
2. Installation and Build is now performed for all supported platforms (linux, macos and windows)
- The results of which are stashed for later use
3. The source files created by the linux build are used as a base for the integrationtests (this is actually how it was done up until now)
4. Creating the .zip- and .tar.gz files is done in parallel to building the windows installer
5. GitHub Releases will now contain the .zip- and .tar.gz files, in addition to the windows installer.
6. Pushing to npm and github is now done in sequence, not in parallel anymore
- The reason is simple: We cannot nest `parallel` statements. Attempting to do so breaks the CI. Since building all the parts for the GitHub release is far more time …
> 👷 📦 Attach ready-to-use platform specific sources to releases

- src/main.ts
- src/test_setup/fixture_providers/setup_ioc_container.ts
- src/test_setup/fixture_providers/test_fixture_provider.ts
- test/0_global_routes/no_http_flag.js
1. Implement `NO_HTTP` environment variable
- When set, this flag will prevent the HttpExtension and the HttpEndpoints for ConsumerAPI and ManagementAPI to be initialized during startup
4. Add tests for the new flag
Closes #438
PR: #442
- Startup the ProcessEngine, without providing the `NO_HTTP` environment variable
- All http endpoints should be available
- Now restart the ProcessEngine and supply the `NO_HTTP` variable (value doesn't matter)
- The process engine should ne accessible through http
> ✨ Add flag for disabling Http endpoints

- src/global_route_configurator.ts
- test/0_global_routes/authority_route.js
- test/0_global_routes/do_not_block_global_route_flag.js
- test/0_global_routes/main_route.js
- test/0_global_routes/sanity_checks.js
1. Implement `DO_NOT_BLOCK_GLOBAL_ROUTE` environment variable, which will cause the router to not use the `/` and `/security/authority` routes
2. Implement `/process_engine` route as an alternative to `/`
3. Implement `/process_engine/security/authority` as an alternative to `/security/authority`
4. Add tests for each new UseCase
Closes #439
PR: #441
- Startup the ProcessEngine, without providing the `DO_NOT_BLOCK_GLOBAL_ROUTE` environment variable
- The routes `/`, `/process_engine`, `/security/authority`, `process_engine/security/authority` should all be working
- Now restart the ProcessEngine and supply the `DO_NOT_BLOCK_GLOBAL_ROUTE` variable (value doesn't matter)
- Only the routes `/process_engine` and `process_engine/security/authority` should be working now
> ✨ Add global routes with `process_engine` prefix

- src/main.ts
Before running the post-migrations, the processes' `cwd` is changes to the directory the runtime is in. 
This is necessary, when embedding the runtime in another application, where the `cwd` may not necessarily be the same as the directory the ProcessEngine is located at.
PR: #448
Easiest way to test this would be to use this feature branch in BPMN Studio.
If the app starts up without a hitch, then everything is fine.
> ♻️ Change cwd to the ProcessEngine's cwd, before running post-migrations

- bpmn/cyclic_timers_disabled.bpmn
- package-lock.json
- package.json
Refactor EventParser
1. Only allow one EventDefinition for each event
2. Add sanity checks for MessageEvents, SignalEvents and TimerEvents
3. Full Changelog: https://github.com/process-engine/process_engine_core/pull/303
Closes #437
PR: #303
- Try deploying ProcessModels with MessageEvents or SignalEvents that are missing references to a message or signal
- Try deploying ProcessModels with TimerEvents that are missing a timer type or value
Each of these cases should fail. Everything else should work.
> 🔒 Prevent use of misconfigured events

- src/main.ts
Enhance support for embedding the ProcessEngine into another application.
1. Allow for startup parameters to be passed as an object with the following parameters:
-  `sqlitePath`: A custom path to where the ProcessEngine should store its SQLite databases
- `logFilePath`: A custom path to where the ProcessEngine should write its logs and metrics
- `container`: A container for registering IoC dependencies. If none is provided, the ProcessEngine will create its own container
- `minimalSetup`: Indicates if only a minimal setup should be done (See 3. and 4.)
2. Alternatively, you can also provide only a string for `sqliteStoragePath` as argument. 
3. Seperate ioc module loading from bootstrapper initialization
4. When `minimalSetup` is provided, the ProcessEngine will only load its ioc modules …
>  ✨ Enhance embedding support

- src/post-migrations/9.1.0-add_flow_node_instance_name_and_lane.ts
1. Fix bug where single quotes need to be escaped in SQL query
PR: #462
Set the name of a flowNode to `dfkfs('dd')` and see that the migrations are successful
> 🐛Fix Postmigrations for flowNodeInstances

- package-lock.json
- package.json
When a claim check runs into a 403 error, the runtime will now print out the identity and the claim that was requested.
Closes #475 
PR: #476
- Run a few requests you are sure will produce a 403
- Note that the logged error will display the identity used, as well as the claim that was requested
> 🔊 Print identity and requested claim when a claim check fails

- package-lock.json
- package.json
- src/modules/environment.ts
This fixes reference issues when setting up the Runtime with a DB environment other than SQLite.
PR: #483
- Start the Runtime with any environment that does not use SQLite
- See that it works
> 🐛 Hotfix: Fix crash during environment setup when using non-sqlite environment

- package.json
1. Fix the 404 npm publish error. 
2. Fix 404 swagger.html when using windows installer
PR: #485 
> 🐛Fix publishing npm package

- .github/workflows/continuous-integration-workflow.yml
> This prevents GitHub Actions from publishing branches that only contain the word `master`, `develop` or `beta`, like `feature/develop_feature_xy` or `release/v9.3.0-beta.1`
1.  Fix Github Actions Workflow Conditions
PR: #490
> 🐛 Fix Github Actions Workflow Conditions

- package-lock.json
- package.json
The `ErrorBoundaryEventHandler` no longer matches the name of a given error against the error attached to the BoundaryEvent.
This means that an error now only has to have a matching code and a message.
Closes #497
PR: #498
- Use an `ErrorBoundaryEvent` that uses a random value for the `name` property and attach it to any kind of activity (easiest would be a ScriptTask)
- Cause an error that uses a different name from the error on the `ErrorBoundaryEvent`
- See that the `ErrorBoundaryEvent` can handle the error
> 🔥Remove error boundary event name matching

- package-lock.json
- package.json
- src/main.ts
- src/modules/console_interface.ts
- src/modules/environment.ts
- src/modules/global_route_configurator.ts
- src/modules/index.ts
- src/test_setup/fixture_providers/test_fixture_provider.ts
1. Adds a command line interface which accepts user input.
2. The following commands are currently accepted:
- `help`: Prints a list of all available commands
- `version`: Prints the current version of the runtime
- `httpconfig`: Prints the runtime's http endpoint settings
- `exit`: Shuts the runtime down
3. Print out the ProcessEngineRuntime's version and http port at startup
4. Move reading of package.json to the `environment` module 
Startup info:
Console commands:
Closes #495 
PR: #499
- Start the runtime
- Type any of the following commands and see that they work as expected
- `help`
- `version`
- `httpconfig`
- `exit`
- Type an invalid command and see the "help" dialog
> ✨ Implement console commands

- src/main.ts
- src/modules/environment.ts
- src/modules/migrator.ts
- src/post-migrations/9.1.0-add_flow_node_instance_name_and_lane.ts
1. Allow to pass multiple path segments to `readConfigFile`
2. Add return type parameter to `readConfigFile`
3. Print address & port info at the top of the ProcessEngine logs
4. Get address & port info from the config files, instead of the HttpExtension
- The HttpExtension is not available, until the Runtime has started up, so we cannot get the actual address from there, since the logs are supposed to be printed at startup
- This will probably not be an issue yet, because if the port is taken, the Runtime will just shut down
- If we make use of port discovery at some point, this issue needs to be revisited, because then the discovered port may not be the same as the one that was configured
Closes #495
PR: #500 
Start the runtime and read the logs.
>  💄 Improve log format

- package-lock.json
- package.json
1. Check Content-Type in Error-Handler
Closes #496
PR: #501
- Run `git checkout ce878a0 && npm i && npm run build && npm start` 
- Send a request to `http://localhost:8000/api/management/v1/process_models` with `Content-Type` `application/json`
- **Notice that the response is `{"message":"test"}` instead of `test`**
> 🐛Fix Response Types of Errors

- package-lock.json
- package.json
1. When an ExternalTask finishes with `{}`, `null` or `undefined`, the resulting `onExit` token of the corresponding ServiceTask will be `{}`. 
2. Fix reference error, when a message received from an ExternalTaskWorker is empty.
Closes #502
PR: #504
- Run an external ServiceTask
- Finish the ExternalTask with `{}`, `null` or `undefined`
- Notice that the ServiceTask`s `onExit` token will always be `{}`
> ♻️ Default empty external ServiceTask results to `{}`

- package-lock.json
- package.json
- test/1_process_engine_core/start_event_cyclic_timers_tests.js
1. Detach BoundaryEvents prior to running `afterExecute` cleanup on decorated Activities
2. Implement resumption for BoundaryEventHandlers
3. When resuming a decorated activity, all attached BoundaryEvents will now be resumed, instead of executed
- This fixes the issue with multiple `onEnter` tokens for a single BoundaryEvent
4. Fix some null reference issues on the base ActivityHandler
5. Unsubscribe from `ExternalTaskFinished` event, when an `ExternalServiceTaskHandler` gets interruped
6. Fix BoundaryEvents token production
- Each BoundaryEvent should now always produce an `onExit` token, either when trigger, or when the activity finishes and removes its BoundaryEvents
7. Refine resumption of ProcessInstances. A ProcessInstance is now considered to be orphaned, if it:
- is in a running …
>  🐛 Fix BoundaryEvent state transitions

- package-lock.json
- package.json
- test/3_consumer_api/process_instances/get_running_instances_for_identity.js
Fix an issue, where ProcessInstances retrieved through the ConsumerAPI would have their values for `correlationId` and `processModelId` switched.
Closes #514 
PR: #515
- Start a few ProcessInstances
- Retrieve them through the Consumer API, using `getProcessInstancesByIdentity`
- See that all properties are as expected
> 🐛 Fix process instance public type conversion

- bpmn/test_consumer_api_correlation_multiple_results.bpmn
- package-lock.json
- package.json
1. Add `findJoinGatewayAfterSplitGateway` to `ProcessModelFacade`, which discovers a matching Join Gateway for a given Split Gateway
- Works for nested gateways of the same type, as well as for nested gateways of a different type
- Works with branches that lead to a dead end (relevant for Exclusive Gateways, which can have branches ending in an EndEvent)
- Ignores paths started by BoundaryEvents
- Works for nested split gateways that have no corresponding join gateway (which can also happen with Exclusive Gateways)
2. When running ParallelSplitGateways, the matching Join Gateway is now discovered beforehand and an instance for it is registered at the ioc container
- This ensures that no duplicated instances for the same Join Gateway are created
3. When starting multiple parallel running …
> ✨ Implement join gateway discovery

- package-lock.json
- package.json
1. GatewayHandlers now wrap their `execute` hooks into an async lock. 
- This is done to prevent race conditions during Join Gateway execution (See references issue).
2. Remove timeout used as workaround from base handlers 
Closes #523
PR: #322
- Create a process that makes use of ParallelGateways - ideally with 3+ branches
- Best use tasks that can be finished simultaneously for each branch (like ExternalServiceTasks with the same topic)
-  Run that process 4-5 times
- When all ExternalTasks have been created, start a Worker that can process these tasks simultaenously
- Note that all FlowNodes of each ProcessInstance will be finished correctly
> ♻️ Add async locks for gateways

- src/main.ts
- src/modules/console_interface.ts
1. Ensure a `http://` prefix is printed with the configured urls at startup
2. Ensure a `http://` prefix is printed with the output of the `httpconfig` command
Closes #529
PR: #530
- Start the application
See this output:
- Type `httpconfig`
Get this output:
> 🔊 http prefix for url info

- package-lock.json
- package.json
Add `depcreated` warning to all obsolete `api/external_task/v1` routes.
Closes #533
PR: #535
- Try accessing any of the old `api/external_task/v1`
- See that you'll get a deprecation warning printed to the console
- Also notice that the response headers will contain values for `Deprecated` and `Link`
Example:
> ♻️ Mark api/external_task/v1 routes as deprecated

- .eslintrc
- .github/workflows/continuous-integration-workflow.yml
- bpmn/send_task_max_retry_test.bpmn
- package-lock.json
- package.json
- test/1_process_engine_core/interprocess_communication_test.js
- test/1_process_engine_core/send_task.js
1. Parse `retryIntervalInMs` and `maxRetries` extension properties for SendTasks
2. Implement Retry mechanism for SendTasks
- The handler will now keep sending the message, until either the maximum number of retries is exceeded or a response was received
- Retry interval defaults to 500ms
- Max number of retries defaults to -1 - i.e. `unlimited`
Closes #538
PR: #539
- Start a ProcessInstance with a SendTask
- See that the SendTask periodically sends its message
- Start a ProcessInstance with a matching ReceiveTask
- See that the SendTask will continue, after the ReceiveTask acknowledges receiving the message
> ✨ Retry send task

- package-lock.json
- package.json
Wait for a `Process Started` notification, before resolving the `startProcessInstance` request.
This prevents a situation, where the request would resolve, before the Process Instance was actually created.
Closes #546
PR: #547
See referenced Issue for details.
> 🐛 Fix early exit bug when starting ProcessInstances
