index.js
* added a listener for unhandled rejections that logs out the error including stack trace
Throw an error inside a promise that is not wrapped by a `try/catch`.
=> Provide Stack Trace for Unhandled Rejection

package.json
Depends on:
* https://github.com/essential-projects/bootstrapper_node/pull/8
* removed `npm rebuild` on `postinstall` hook
* updated `bootstrapper_node` to a new version without deasync 
Run `npm install -g @process-engine/process_engine_runtime@feature~fix_windows_build` on a windows machine.
There should be no errors during installation.
After the installation you should be able to start a Process Engine Server by running `process-engine` from any location.
=> Fix Windows Build

README.md
* added remarks concerning the windows installation and possible problems during installation
=> Add windows setup remarks

.ci-tools/package.json, .ci-tools/publish-github-release.js, Jenkinsfile
**Changes:**
1. Add stage `publish github release`.
2. Remove stage `lint` (currently there's nothing to lint).
3. Add `ci-tools` based on the `ci-tools` of `BPMN-Studio`.
4. Change `NPM_RC_FILE` from `process-engine-ci-token` to `developers5minds-token` (again taking `BPMN-Studio` as an example).
If there are no changes requested, I'd like to field test this in the next release.
Until then, this feature branch should already get built using the changes from this `Jenkinsfile`. 
The Jenkins job should run without errors and the package should get published to the registry.
=> Add Jenkinsfile to Improve Pipeline

index.js
**Changes:**
1. Fixed missing ioc_module reference
PR: #14
---
Start the application via command `process-engine`.
The easiest test is to open a browser and visit localhost:8000
* Result will be Cannot GET /
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
=>  🐛 Fix ioc modules

config/postgres/services/mail.json, config/sqlite/services/mail.json, package.json
:tada: **Thanks for submitting this Pull Request**
Please provide a list including your changes.
To help us to create a meaningful Changelog, we agreed
to use an emoji-based commit-style. Use the [Emojis](#emojis)
we provided below.
Fill out the following, provide reference to issues
and this PR- we will use this as merge commit message-body
and the title of this PR as commit-headline:
---
**Changes:**
1. Add configuration file for the MailService
**Issues:**
Closes #https://github.com/process-engine/bpmn-studio/issues/854
PR: #19
---
- use this branch as version in the package.json of bpmn-studio 
- run a send mail process
<details>
<summary>
:warning: Before merging please click …
=> ✨ Add MailService Configuration

index.js, package.json
**Changes:**
- Ensure that the selected workDir exists, before using it
PR: #26
Ensure that the workDir does not exist and the start the Runtime.
Everything should work as expected.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre> …
=> 🐛 Fix environment initialization

package.json
**Changes:**
1. Fix an issue, where suspended user tasks caused the process instance not to appear in the list of active correlations.
**Issues:**
Closes #27 
PR: #29
Run a process with a user task and wait until it is suspended. Then check the list of active correlations.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> 🐛 Fix active correlation retrieval

package.json
**Changes:**
1. Update Platform-Folders to 0.2.7
**Issues:**
Closes #32 
PR: #33
- Run `npm install`
- Run `npm install` again
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most …
=> ⬆️ Update Platform-Folders

migrator.js, package.json, sequelize/migrations/flow_node_instance/4.2.0-4.3.0-flow_node_instances.js
**Changes:**
1. Fixes an issue, where the use of loggerythm caused the migration to fail, when starting the runtime through the BPMN studio
PR: #36
Use BPMN Studio to startup the runtime. This will cause the migrations to be executed.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> 🐛 Fix migration script logging

migrator.js, package.json, sequelize/migrations/flow_node_instance/4.2.0-4.3.0-flow_node_instances.js
**Changes:**
1. Ensure windows compatibility for migrations.
2. Add fallback, in case a table to migrate does not exist.
PR: #39
Start the backend on windows.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details> …
=> ♻️ Add windows support to migrations

package.json
**Changes:**
1. Fix empty Camunda Property filtering
2. Fix finishing of user tasks
3. Fix validating user task payloads
**Issues:**
Closes #25
Closes #34
PR: #40
- Start the backend
- Try to parse a process model with empty camunda property tags
- Start multiple user tasks across multiple process instances with the same user task id
- Finish only one of them and see that no other user task has been touched
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit …
=> ⬆️ Release 2.0.4

bin/index.js, package.json
**Changes:**
1. Add shebang to bin/index.js file.
**Issues:**
Closes #42 
PR: #43 
Try starting the runtime from the console and see that the shebang is being considered.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details> …
=> :sparkles: Add Shebang to Startup File

package.json
**Changes:**
1. Apply a fix for the ConsumerApiCore package, which fixes an issue with parsing suspended UserTasks. 
See issue for details.
**Issues:**
Closes #41 
PR: #44
See reproduction steps as described in the issue. 
Note that querying suspended UserTasks no longer fails.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> 🐛 Fix user task parsing

package.json
**Changes:**
1. Adds support for `IntermediateTimerEvents`
2. Fix the handling of cycle-timers with the `TimerBoundaryEvent`
3. Enhance the `FlowNodeInstanceService` of the Core Package with a function for querying specific FlowNodeInstances by CorrelationId, ProcessModel and FlowNodeId.
**Issues:**
Closes #37
PR: #52
Start a ProcessModel that uses IntermediateTimerEvents.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of …
=> ✨ Add intermediate timer events

package.json, scripts/database-non-docker/README.md, scripts/database-non-docker/create_role_and_db.sql, scripts/database-non-docker/setup_db_linux_unix.sh, scripts/database-non-docker/setup_db_windows.cmd, scripts/database/Dockerfile.skeleton, scripts/database/README.md, scripts/database/postgres_docker.js, scripts/database/skeleton.sql
**Changes:**
Imports the scripts for handling postgres databases from the old skeleton repository.
This should be the final step in rendering that repository completely obsolete.
**Issues:**
Closes #72
PR: #81
- Navigate to `scripts/database`
- Run `node postgres_docker.js start` or `node postgres_docker.js reset` for starting or resetting the docker container containing the postgres database
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy …
=> ⚡️ Add database scripts

package.json
Requires: https://github.com/process-engine/consumer_api_core/pull/62
**Changes:**
Fixes an issue, where loading many user tasks through the consumer API could take a very long time. See issue for details.
**Issues:**
Closes #62
PR: #79
Try loading lots of suspended UserTasks through the Consumer API.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text …
=>  ⚡️ Increase usertask conversion performance

Jenkinsfile
**Changes:**
1. Execute tests inside a docker container to avoid port collisions
**Issues:**
Closes #96 
PR: #97 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
=> :construction_worker: Run Tests Inside A Docker Container

package.json
---
**Changes:**
1. Bump the version of flow_node_instance.repository.sequelize to v4.3.1
**Issues:**
PR: #PullRequest
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> :arrow_up: bump flow_node_instance.repository.sequelize to 4.3.1

package.json, test/6_external_task_api/fetch_and_lock.js
**Changes:**
1. Fix an issue, where parsing process model logs caused an error with moment.
2. Fix test  cleanup for the `fetchAndLock` tests.
PR: #104
All should work as before, except that moment will no longer throw an error, when trying to parse ProcessModel logs.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some …
=> 🐛 Fix ProcessModel log parsing

package.json
---
**Changes:**
1. Throw a 404 error instead of a 500 Error when a flow node instance with a given ID was not found for the requested Process Instance.
**Issues:**
Closes #103 
Related PR: https://github.com/process-engine/flow_node_instance.repository.sequelize/pull/14
PR: #106
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get …
=> 🐛 Fix throwing of a 404 when a specific FlowNodeInstance was not found

test/2_management_api/token_history/token_history.js
---
**Changes:**
1. This PR adds a test which checks, if the correct error code and message is thrown, when the
user tries to access a FlowNodeInstance which does not exists in a given correlation. 
PR: #113
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example …
=> Add a test for the correct error message when trying to access a FlowNodeInstance which does not exists

bpmn/test_management_api_logging_simple_process.bpmn, test/2_management_api/log_history/log_history.js
---
**Changes:**
1. Adds some basic tests for the `getProcessModelLog()` method from the Consumer API. 
PR: #114 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
=> ✅ :white_check_mark: add tests for the getProcessModelLog method

config/postgres/http/http_extension.json, config/sqlite/http/http_extension.json, config/test/http/http_extension.json, package.json
Requires:
https://github.com/essential-projects/http_extension/pull/13
**Changes:**
1. Allow to pass options to the cors middleware. These will be retrieved from the HTTP extensions' config.
2. Refactor the expected CORS config to the following structure: 
```json
"cors": {
"enabled": true,
"options": {
"allowedHeaders": [
"Content-Type",
"Authorization"
],
"credentials": true,
"methods": "GET,HEAD,OPTIONS,PUT,PATCH,POST,DELETE",
"origin": "*",
"preflightContinue": false
}
}
```
**Issues:**
Closes #108 
PR: #110
Perform CORS calls when the runtime is started. Try out various configurations for the HTTP extension to ensure functionality.
<details>
<summary>
:warning: Before merging please click here to expand and follow the …
=> ✨ Allow cors configuration

bpmn/empty_lane_test.bpmn, bpmn/test_management_api_import_empty_lane.bpmn, package.json, test/1_process_engine/parse_bpmn_model_to_object_model.js, test/2_management_api/process_models/update_process_definitions_by_name.js, test/3_consumer_api/process_instances/sanity_checks.js
**Changes:**
1. Fix parsing of ProcessModels that contains an empty lane.
**Issues**
Fixes #115 
PR: #116 
Run the tests.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used …
=> 🐛 Fix parsing of ProcessModels which contains an empty lane

config/postgres/http/http_extension.json, config/sqlite/http/http_extension.json, config/test/http/http_extension.json, package.json
**Changes:**
Due to some problems with using CORS with the BPMN studio, the header check for CORS has been disabled.
PR: #122
Run the tests.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a …
=> 🔥 Disable header check for CORS

package-lock.json, package.json, test/1_process_engine/end_events.js, test/1_process_engine/interprocess_communication_test.js, test/1_process_engine/start_event_tests.js
Requires:
https://github.com/process-engine/process_engine_contracts/pull/74
https://github.com/process-engine/process_engine_core/pull/186
**Changes:**
1. Use a signal's or message's name, instead of its ID, for subscribing to the corresponding events.
**Issues:**
Closes #117 
PR: #121
Inter-process communication with events and signals should now be possible.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this pull …
=>  ♻️ Use name of signals and messages

package-lock.json, test/1_process_engine/start_event_tests.js
**Changes:**
1. Poll for suspended FlowNodeInstances before running the tests for MessageStartEvents and SignalStartEvents. 
This should help avoid running into the timeout issue that sometimes causes Jenkins builds to fail.
**Issues:**
Closes: #123
PR: #127
Run the tests.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> ✅🐛 Poll for suspended flow nodes in the start event tests

Jenkinsfile
**Changes:**
1. Archive package-lock.json file
**Issues:**
PR: #149 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> :construction_worker: Archive package-lock.json After Installing

bpmn/parallel_gateway_test.bpmn, package.json, test/1_process_engine/boundary_event_message_test.js, test/1_process_engine/boundary_event_signal_test.js, test/1_process_engine/intermediate_event_tests.js
**Changes:**
1. Update dependencies
**Issues:**
Closes #152 
PR: #154
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1135**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand …
=> 🐛 Fix Token Merging of Parallel Gateway

package-lock.json, package.json
**Changes:**
Fix an issue, where a SubProcess would not get the ID of the ParentProcess, thus making it impossible to distinguish between normal Processes and Subprocesses, or Processes that were called through a CallActivity.
PR: #156
- Run a few CallActivities
- Check the databases and see that each CallActivity now has a parentID. 
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre> …
=> 🐛 Fix passing of ParentProcessId to SubProcess

package.json, test/1_process_engine/interprocess_communication_test.js
**Changes:**
Fix an issue, where ExclusiveSplitGateways that encountered an error did not have their state changed accordingly.
**Issues:**
Closes #158 
PR: #159
Run Processes with erroneously configured ExclusiveSplitGateways and see that these will no be persisted in an "error" state when they are run.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong …
=> 🐛 Fix ExclusiveSplitGateway onError state change

package-lock.json, package.json
**Changes:**
✨ Add dynamic timer experessions to timer related FlowNodeHandlers.
This allows to use token values with the timers.
**Issues:**
Closes #173 
PR: #178 
Try to use timer events with dynamic token expressions.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> ✨ add dynamic timer expressions

package-lock.json, package.json, sequelize/migrations/flow_node_instance/07_flow_node_instance.js
**Changes:**
1. Refrain from using `Object.assign` when merging token results for a ParallelGateway.
- This fixes an issue where the ProcessTokenFacades contents would get wiped upon leaving the ParallelJoinGateway.
2. Add missing result tokens for ParallelJoinGateway. 
3. Apply fix for FlowNodeInstance repository to allow null-values for `flowNodeType`
4. Make the backup table in the latest FlowNodeInstance migrations less restrictive
- This is done to solve some migration errors we are experiencing on windows, due to very old data in that particular table.
**Issues:**
Closes #180
PR: #181
ParallelGateways will no longer wipe the ProcessTokenFacade. Using `token.current` and `token.history` is now possible again.
<details> …
=> 🐛 Fix Token for Parallel Gateways

package-lock.json, package.json, sequelize/migrations/flow_node_instance/08_flow_node_instance.js
Requires:
https://github.com/process-engine/flow_node_instance.repository.sequelize/pull/25
**Changes:**
1. Move the following columns from the `ProcessToken` table to the `FlowNodeInstance` table:
- `processInstanceId`
- `processModelId`
- `correlationId`
- `identity`
- `callerId` => was renamend to `parentProcessInstanceId`
2. Add a migration script to cover these changes.
**Issues:**
Closes #140 
PR: #190
This is a purely internal change, so all should work as before.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix …
=> ♻️ Refactor datamodels for FlowNodeInstance and ProcessTokens

bpmn/intermediate_event_link_test.bpmn, bpmn/intermediate_event_timer_test.bpmn, package-lock.json, package.json, test/1_process_engine/intermediate_event_tests.js
**Changes:**
1. Implement contracts and handlers for`IntermediateLinkCatchEvent` and `IntermediateLinkThrowEvent`.
2. Fix state transitions for `IntermediateTimerCatchEvents`, after the attached timer has expired.
3. Add tests for `IntermediateLinkCatchEvents` and `IntermediateLinkThrowEvents`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/163
Closes #193 
PR: #192
Use the new handlers and/or run the tests.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code> …
=> ✨ Implement link events

bpmn/process_model_without_lanes.bpmn, package-lock.json, package.json, test/4_deployment_api/import_from_file.js, test/4_deployment_api/import_from_xml_local.js, test/4_deployment_api/import_from_xml_remotely.js, test/4_deployment_api/sanity_checks.js
**Changes:**
Fixes an issue, where it was impossible to query ProcessModels with empty laneSets or no laneSets at all.
**Issues:**
Closes #215
PR: #217
Try deploying ProcessModels without any lanes.
=> 🐛 Fix claim checks on empty lane sets

package.json
**Changes:**
1. Update Sqlite3
PR: #221
**- Have a look at https://github.com/process-engine/bpmn-studio/pull/1306**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis. …
=> ⬆️ Update Sqlite3

bpmn/modell_parser_cyclic_timer_test.bpmn, bpmn/modell_parser_timer_invalid_date.bpmn, bpmn/modell_parser_timer_invalid_duration.bpmn, package-lock.json, package.json, test/1_process_engine/parse_bpmn_model_to_object_model.js
**Changes:**
1. Adds a validation for the input of a timer definition which, currently, has to be in the ISO8601 format. 
**Issues:**
Closes #195 
PR: #223 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text …
=> ✨ Add a Validation for Timer Input Values

package.json
---
**Changes:**
1. Bumps the version of the Runtime to 5.4.0 to mark all pre releases with the right version.
**Issues:**
PR: #224
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> 📕 Bump Runtime Version to 5.4.0

package.json
**Changes:**
Fix an issue where empty values in a UserTask's enum-type FormField caused the ProcessModel parser to crash.
PR: #242
=> 🐛 Fix user task form field enum value parsing 

.gitignore, Jenkinsfile, inno-installer.iss, installer/README.md, installer/inno-installer.iss, installer/start_process_engine_runtime.bat, package-lock.json, package.json
**Changes:**
1. Add script to create binary exe for windows
2. Add Inno Setup configuration
3. Create windows install in build pipeline
4. Add documentation 
**Issues:**
PR: #261 
Try to follow the processed as described in the installer/README.md file.
=> :sparkles: Windows Install Binary

bpmn/user_task_test.bpmn, package-lock.json, package.json, test/1_process_engine/user_task_tests.js
**Changes:**
1. Fix an issue which caused ManualTasks and UserTasks to be suspended before they had created their subscriptions on the EventAggregator.
- This could lead to situations, where a UserTaskHandler missed a `FinishUserTask` notification and remained suspended indefinitely.
2. Add validation for a UserTask's FormField expressions, to ensure a FormField doesn't attempt to use non-existing token values.
3. Fix ErrorEventDefinition parsing.
**Issues:**
Closes #240
Closes #263
PR: #271
Try executing a UserTask with a FormField, which tries accesing non-existing token values (like `${token.a.b.c.whatever}`).
=> 🔒 ♻️ Validate UserTask payloads

package-lock.json, package.json
**Changes:**
1. Configure `retry` option for Sequelize Connections
- Retry is to be done for `BUSY` errors.
- Max retry amount is 50.
**Issues:**
Closes #287 
PR: #290
Try executing ProcessModels that use a very large amount of parallel running branches.
=> 🔧 Configure retry-option for queries failing with SQL_BUSY

package-lock.json, package.json, scripts/post-migrations/7.1.1-fix_sqlite_database_contents.js, scripts/post-migrations/setup/environment_handler.js, sequelize/migrations/correlation/01_correlations.js
**Changes:**
1. Fix a typo in one of the Correlation migration scripts
2. Provide a post-migration script which fixes data consistency errors that occured with the Release of v7.1.0 and were fixed with [Hotfix 7.1.1](https://github.com/process-engine/process_engine_runtime/releases/tag/v7.1.1).
3. Provide a basic setup for all post-migration scripts that we may need in the future.
**Issues:**
Closes #275 
PR: #289
- Store [these databases](https://github.com/process-engine/process_engine_runtime/files/2951990/Archiv.zip) somewhere on your system (ideally at the location where you usually put your SQLite databases, but any other path will do just fine)
- If you examine them, you'll notice a `ProcessDefinitions` table in the `flow_node_instance.sqlite` database and a `FlowNodeInstances` and …
=> 🐛 Provide db patch script for release v7.1.1

README.md
**Changes:**
Additional information about where the logfiles and metrics are stored.
PR: #292
Read the text.
=> 📖 Add infos about created application files

package-lock.json, package.json
**Changes:**
1. Update mocha to v6.
PR: #293
Run the tests.
=> ⬆️ Update mocha to v6

package-lock.json, package.json
**Changes:**
Implement the fix for CallActivity ProcessTermination from the [ProcessEngineCore package](https://github.com/process-engine/process_engine_core/pull/260).
PR: #294
This is easiest to test with the BPMN Studio:
- Create a Process with a CallActivity.
- Create a Subprocess for that CallActivity - ideally with a suspendable task, so you can follow its progress.
- Manually stop either the subprocess, or the parent process with the CallActivity.
- See that both processes will terminate correctly.
=> ✨ CallActivity termination

package-lock.json, package.json
**Changes:**
1. Correlations that were created with the dummy token are now always included in the correlation list.
2. Fix an issue that prevented `SubprocessHandlers` from resuming their Subprocesses.
PR: #295
- Create some correlations with the dummy token.
- Make a request for correlations with a different token.
- See that the result set will contain the correlations from the dummy token as well.
=> ♻️ Always return correlations created with the dummy token 

bpmn/intermediate_event_receive_tests.bpmn, bpmn/intermediate_event_send_tests.bpmn, package-lock.json, package.json, test/1_process_engine/interprocess_communication_test.js
**Changes:**
1. Add `inputValues` property to `IntermediateThrowEvent` and `EndEvent` models.
2. Add token expression handling to `IntermediateThrowEvent` and `EndEvent` handlers.
3. Remove duplicated FlowNodeInstance suspension from `IntermediateSignalCatchEventHandler`.
4. Add tests for covering MessageEvents and SignalEvents with a customized payload.
**Issues:**
Closes #296
PR: #298
Run the tests.
=> ✨ Allow for customized event payloads

package-lock.json, package.json
**Changes:**
Abort ExternalTasks with an error, if the corresponding ProcessInstance is prematurely aborted.
PR: #302
- Start a ProcessInstance with an ExternalTask.
- Wait until that task is reached and suspended.
- Stop the ProcessInstance.
- See that the task is no longer active.
=> 🐛 Hotfix/v7.3.1

package-lock.json, package.json
**Changes:**
Fix an issue with the Promise-chains of the external ServiceTask handler that prevented an orderly interruption.
PR: #303
Aborting external ServiceTasks now works correctly again.
=> 🔖 Hotfix/v7.3.2

package-lock.json, package.json
**Changes:**
1. Add a missing `persistOnError` call to the external ServiceTask handler.
2. Fix Promise-rejection in external ServiceTask resumption.
3. Use the correct token payload for the external ServiceTask's `onError` state transiton.
**Issues:**
Closes #307
PR: #308
- Start a Process with an external ServiceTask
- Wait until the ServiceTask has created an ExternalTask
- Finish that ExternalTask with an error
- See that the corresponding ServiceTask is finished with an error and gets an appropiate token.
=> 🐛 Fix on error state transition for external service tasks

package-lock.json, package.json, sequelize/migrations/flow_node_instance/2019-04-03_flow_node_instance.js
**Changes:**
1. Change the schema type for `FlowNodeInstance.error` to `TEXT`
- Using `STRING` here is insufficient, because it would limit the column to 255 chars with postgres. This is not enough for error objects.
2. Add migration script to cover this change.
3. Apply refactoring of the base FlowNodeHandlers from the ProcessEngineCore package.
**Issues:**
Closes #314 
PR: #315
Testing the refactored error column:
- Run a process and provoke an error on a FlowNode, using Postgres as database
- See that the error gets stored correctly.
The refactoring of the base FlowNodeHandlers shouldn't be visible to outside users at all.
=> ♻️ Refactor base flow node handlers

Jenkinsfile
1. Revert 30405d1 
2. Revert ecc240e 
3. 👷 Correct GitHub Credential Id
PR: #327 
Watch some Jenkins Builds and see that they work again.
=> 👷 Fix Builds

README.md
Fix a dead link in the Readme.
PR: #326
=> 🐛 Fix dead link in Readme

package-lock.json, package.json
1. Fix resumption of FlowNodes, when dealing with multiple FlowNodeInstances for the same FlowNode within the same ProcessInstance.
2. Fix an issue with ExclusiveGateway resumption, where the default SequenceFlow was not accounted for.
3. Remove some duplicated ProcessToken creations that occurred during FlowNodeHandler resumption.
Closes #332
PR: #341
Use this version of the Runtime with BPMN Studio.
Follow the steps described here:
https://github.com/process-engine/process_engine_runtime/issues/332
See that the ProcessModel will now be executed and resumed correctly.
=> 🐛 Fix resumption of FlowNodes with multiple FlowNodeInstances

Jenkinsfile, package-lock.json, package.json
Stellt das Jenkinsfile auf den neuen Release-Prozess mithilfe der `ci_tools` um.
PR: #382
=> 👷 Add ci tools to jenkinsfile

Dockerfile, Jenkinsfile, package-lock.json, package.json
1. Add Docker Build Step
PR: #392
- Have a look at [this build](https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fprocess_engine_runtime/detail/feature%2Fadd_docker_build_step/52/pipeline)
- Run `docker pull 5minds/process_engine_runtime:v8.5.0-feature-bb5d59-jzjxwzj8` and `docker run -p 8000:8000  5minds/process_engine_runtime:v8.5.0-feature-bb5d59-jzjxwzj8`
- **Notice that the runtime will be running in version 8.5.0-feature-bb5d59-jzjxwzj8**
=> ✨ Add Docker Build Step

package-lock.json, package.json
1. Refactor TimerEvent handling in ProcessEngineCore (See: https://github.com/process-engine/process_engine_core/pull/292)
PR: #393
=> ♻️ Improve TimerFacade and TimerDefinition parsing

bpmn/parallel_gateway_finish_test.bpmn, package-lock.json, package.json, src/test_setup/test_services/parallel_gateway_test_service.ts, test/1_process_engine/parallel_gateway_test.js
1. Fix Join Gateway Finish Check
Closes #389
PR: #398
=> 🐛 Fix Join Gateway Finish Check

package-lock.json, package.json
1. Fix and refine ErrorBoundaryEvent error matching
Closes #408 
PR: #413
The ErrorBoundaryEvent should now work as expected.
=> 🐛 Fix ErrorBoundaryEvent matching

README.md
Update the Readme:
1. Update contact info
2. Add info about global routes
3. Add info about environment parameters
4. Add info on how to switch databases
5. Add info about the ready-to-use sources attached to each release
PR: #445
=> 📖 Improve Readme 

package-lock.json, package.json
1. Fix Changing ParallelJoinGateway State on Error
Closes https://github.com/process-engine/process_engine_runtime/issues/459
PR: #464
- Run this process:
[parallel_join_gateway_test.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3743742/parallel_join_gateway_test.bpmn.zip)
- **Notice that the state of the ParallelJoinGateway changes to error as soon as an error occurs**
=> 🐛 Fix Changing ParallelJoinGateway State on Error

package-lock.json, package.json
1. Resume ProcessInstances by ProcessInstanceState Instead of FlowNodeStates
Closes #458 
PR: #465
- Check that processes still get resumed
=> 🐛Resume ProcessInstances by ProcessInstanceState Instead of FlowNodeStates

Dockerfile, Jenkinsfile, scripts/pack_sources/pack_to_tarball.js
1. Add Docker Build Without `npm install`
PR: #467
=> ✨ Add Docker Build Without `npm install`

Jenkinsfile
1. Fix Docker Build Step
PR: #477
- **Have a look at this build: https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fprocess_engine_runtime/detail/feature%2Ffix_typo_in_jenkinsfile/3/pipeline/560**
=> 🐛 Fix Docker Build Step

package-lock.json, package.json
1. Fix ReceiveTask state transition to "finished"
Closes #471 
PR: #472
See referenced issue.
=> 🐛 Fix ReceiveTask state transition to "finished"

package-lock.json, package.json, test/3_consumer_api/external_tasks/fetch_and_lock.js, test/4_DEPRECATED/external_task_api_client/fetch_and_lock.js
1. The ProcessEngineCore has been updated to Typescript 3.7. As a result, a lot of the base code has been changed.
2. Fix non-interrupting BoundaryEvent continuation
3. Log resumption of UserTasks, ManualTasks, EmptyActivities and ReceiveTasks
Full Changelog: https://github.com/process-engine/process_engine_core/pull/312
Closes #481
PR: #480
The only change that should be visible to the outside observer is the fact that ExternalServiceTasks without any kind of payload will no longer have that property attached to them.
Everything else should work as before.
=> ⬆️ Upgrade ProcessEngineCore to TypeScript 3.7

.github/workflows/continuous-integration-workflow.yml
1. Adjust Slack Notifications
PR: #489 
=> ♻️ Adjust Slack Notifications

.github/workflows/continuous-integration-workflow.yml
1.  Add Release Notes Announcement
PR: #505
- **Have a look at the `#bpmn-studio_test-announcement-channel` slack channel.**
=> ✨ Add Release Notes Announcement

.github/workflows/continuous-integration-workflow.yml, package-lock.json, package.json
1. Tag the Docker Image with latest and major runtime version
PR: #513
=> 🐳 Tag the Docker Image with latest and major runtime version

package-lock.json, package.json
1. Remove event subscriptions from ParallelJoinGatewayHandler, after it finished or was interrupted
2. Make all FlowNodeHandlers subscribe to ProcessInstance errors
3. When a ProcessInstance gets interrupted by an unhandled error, all FlowNodeInstances immediately exit with an "error" state 
- This ensures that all FlowNodeInstances of an errored ProcessInstance get cleaned up properly
Full Changelog:
https://github.com/process-engine/process_engine_core/pull/319
Closes #517
PR: #519
Use  [this diagram](https://github.com/process-engine/process_engine_core/files/4160770/EventTesting.bpmn.zip)
1) 
- Let the TimerBoundaryEvent expire
- All active FlowNodeInstances, including the ParallelJoinGateway, will be terminated
2)
- Finish the UserTask and let the following ScriptTask throw an error …
=>  ♻️ Refactor Event Subscription handling

.github/workflows/continuous-integration-workflow.yml, config/test-mysql/.my.cnf, package.json
1. Use the MySQL Docker script. for the Github Actions MySQL tests.
PR: #540 
=> 🐛 Use MySQL Docker Script for Github Actions

.gitignore, Dockerfile
1. Fixes an issue, where the `/api/consumer/info` route results in an error, while the runtime is running inside a docker container. 
Closes #537 
PR: #543 
* Build the Docker Container
* Start the Docker Container
* Open the `/api/consumer/info` route
* See, that the information is returned.
=> 🐛 Fix accessing Consumer API info route through docker

package-lock.json, package.json
Fix a critical error that prevented the resumption of FlowNodeInstances that followed a triggered BoundaryEvent.
Part of https://github.com/process-engine/process_engine_runtime/issues/544
PR: #545
See the reproduction steps described in the issue.
=> 🐛 Fix resumption of activities that followed a triggered BoundaryEvent

package-lock.json, package.json
##Changes
1. Update dependency to apply the multiline error message bugfix
Closes #https://github.com/process-engine/bpmn-studio/issues/2010
PR: #557 
- run a diagram which produces multiline error messages
- open the BPMN Studio logviewer
- see that the error is shown correctly
=> 🐛Fix multiline error messages

.github/workflows/continuous-integration-workflow.yml
1. Announce release after build is done
Closes #518
PR: #559
=> ♻️Announce release after build is done
